### ISSUE TITLE
not detecting `package.json` when in a subdirectory

### ISSUE THREAD

**Issue by danielroe** [unjs/pkg-types#114]
https://github.com/unjs/unstorage/issues/172#issuecomment-1463849490

example: https://github.com/AloisSeckar/demos-nuxt

still need to triage issue, but it might be related to being on a windows machine 🤔

**Comment by pi0** [comment]
@danielroe do you rememebr more of context for this issue? What util fails `resolvePackageJSON` seems to use lookup.

(otherwise maybe we can close until see another issue?)

**Comment by danielroe** [comment]
Were you not able to reproduce with the reproduction link?

**Comment by pi0** [comment]
i couldn't find a pkg-types repro... However if issue was about windows only, it might have been fixed with pathe releases. we might enable test matrix for windows to try.

**Comment by pi0** [comment]
https://github.com/unjs/pkg-types/pull/205
