### ISSUE TITLE
Use of git repo as workspace package breaks Nuxt dev

### ISSUE THREAD

**Issue by peteromano** [unjs/pkg-types#121]
### Environment

pkg-types 1.0.2
Nuxt 3.4.1
Node 16.20.0 (Docker node:16-alpine)
pnpm 8.3.0

### Reproduction

* Create root pnpm workspace
* Create apps directory
* Add to pnpm-workspace.yaml:

```
packages:
  - 'apps/**'
```

* Add basic Nuxt 3 setup under /apps:

```
{
  "name": "nuxt-app",
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare; sed -i \"s/\\.git\\/config/$(date +%s)/g\" ../../node_modules/pkg-types/dist/index.mjs"
  },
  "devDependencies": {
    "nuxt": "^3.4.1"
  }
}
```

<img width="302" alt="image" src="https://user-images.githubusercontent.com/392387/233198805-314b48fa-8e97-4aa9-9156-0ae65ab8f57a.png">

* Run `git init` in /apps/nuxt-app directory
* Run `pnpm i --shamefully-hoist && pnpm --stream --filter *-app dev --no-clear`

### Describe the bug

Nuxt build dependency resolution breaks (see Logs below.)

We want to be able to use workspace packages as normal git repos during development.

In general, side effect behavior for user having _any_ specific file in their directory shouldn't be the user's problem...

Need a configuration (env var?) or such to be able to switch this behavior, or do a more detailed tree lookup for nested git repos or node_modules?

### Additional context

The offending code: https://github.com/unjs/pkg-types/blob/6b7b8fa098dda95b5c5a7ee4cea4dbcab281daf3/src/index.ts#L129

And the "solution" (in nuxt-app package.json): 
```
"scripts": {
  ...
  "postinstall": "nuxt prepare; sed -i \"s/\\.git\\/config/$(date +%s)/g\" ../../node_modules/pkg-types/dist/index.mjs"
}
```

To be clear: a workspace subpackage with _no_ .git/config file (or using the above hack) works 100%.

### Logs

![image](https://user-images.githubusercontent.com/392387/233199774-3a954432-e03d-4249-a545-158209a4ae22.png)

**Comment by peteromano** [comment]
@pi0 What do ya think?

**Comment by pi0** [comment]
Hi dear @peteromano sorry for delay on answering this.

If you still have this issue, please consider helping to make a reproduction and make a new issue to check 🙏🏼
